LineLength:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
SpaceAroundEqualsInParameterDefault:
  Enabled: false
StringLiterals:
  EnforcedStyle: double_quotes
