version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1

    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"

    steps:
      - checkout

      - ruby/install-deps # use the ruby orb to install & cache dependencies

      - ruby/rspec-test # use the rubo orb to run specs


workflows:
  version: 2

  commit:
    jobs:
      - build
